### PR TITLE
ES2015 implementation

### PR DESCRIPTION
**Pull request by targos**
Still a work in progress, I will squash the commits when it is ready.

This changes the Matrix implementation to use ES2015 classes, which allow to create our own extension of the Array class. The current implementation uses the `__proto__` property as a workaround. It is both bad practice and bad for performances.

The major drawback of classes is that they are not available in Node.js 0.12 and some browsers (especially Safari). Luckily, Node.js v4 will be released by the end of the week and the next version of Safari will support classes.

### CODE REVIEW

**Comment by targos** [comment]
It is ready. I think the only breaking change is with the Matrix constructor. Now it is not possible to give a 2D array and have it magically transformed to a Matrix. It will always create a new instance.

@mljs/collaborators Somebody please take a look. Now I am going to check with different browsers if it works as expected

**Comment by targos** [comment]
OK so here is the result:

Chrome: No problem
Edge: No problem
Safari: Two problems
 * Does not support let / const. This can be easily fixed by using var again.
 * Does not support extending Array. This is blocking.
Firefox: Does not support classes at all. This is blocking.

**Comment by lpatiny** [comment]
Nightly build of firefox support classes.
https://developer.mozilla.org/en/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_6_support_in_Mozilla
Is it easy to test with nightly build ?

**Comment by targos** [comment]
I tested nightly build. They don't support `super()` so extending Array is impossible

**Comment by targos** [comment]
I created a v1.x branch to work on the issues with ES5 code.
We can still merge this to master and wait until it works in Firefox

**Comment by targos** [comment]
After discussion with @lpatiny we think it would be difficult to maintain 2 branches. Also, we would lose the performance gain in Chrome and Edge.

So we propose to go on with this and abandon ES5 support. It means that as soon as `ml-matrix` is included in ML, the library will stop working in Firefox and Safari.
@mljs/collaborators thoughts ?

**Comment by andcastillo** [comment]
Well, I've needed to update all my old new Matrix.ones(...) and so on, that I guess was a mistake. 
About the support on Safari, seems something bad. ¿How long do you think it will take till it becomes compatible?
Anyway, I only use Chrome for the visualizer.
Moreover, I don't know if it the good place, but I getting this error trying the new version in the curve-fitting project: 

/Users/acastillo/git/curve-fitting/node_modules/ml-matrix/src/dc/lu.js:144
            X = value.subMatrixRow(this.pivotVector, 0, count - 1),
                      ^
TypeError: value.subMatrixRow is not a function

That is a bug? Or it is only me?

**Comment by targos** [comment]
@andcastillo regarding subMatrix, can you open a new issue ? I forgot to reimplement it and there is no test yet for the LU decomposition

**Comment by targos** [comment]
For Safari, there are several possibilities:
* They implement the missing features before the release of OSX 10.11. The release will happen in less than a month so I doubt it.
* They update Safari later to add the features. This is very unlikely, usually they just do security fixes.
* They add the feature in the next Safari. We won't have it before next year (when OSX 10.12 is released)
* They add the feature even later...

**Pull request merged**
