### PR TITLE
Documentate and modify function solve

### PR DESCRIPTION
**Pull request by jajoe**
I added documentation to QR and SVD, and add a facultative parameter to the function solve to enable to use SVD. SVD is useful when the matrix A (in the least square problem Ax = b) is singular or ill-conditioned. To compute the inverse of the matrix A, SVD is useful too if A is singular.

### CODE REVIEW

**Comment by targos** [comment]
It's not critical but next time please use the "Squash and merge" option and rewrite the commit message following our [guidelines](https://github.com/mljs/ml/blob/master/CONTRIBUTING.md#commit-guidelines)

**Comment by jajoe** [comment]
the guidelines are for every commit or we just rewrite before merging ?

**Comment by targos** [comment]
They are for every commit that end up in the master branch. You can rewrite before merging, either with the squash and merge option or locally (with `git rebase -i origin master`) if you want to keep separate commits.

**Comment by targos** [comment]
It's important especially for "fix", "feat" and "BREAKING CHANGES" because that influences the version number of the next release and the changelog.

**Pull request merged**
